version: "3.8"
services:
  db:
    image: mysql:8.0.27
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_app
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
      
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./server/:/go/src/
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true
    stdin_open: true

  migrate:
    build:
      context: ./server/
      dockerfile: Dockerfile
    working_dir: /go/src/db/migrate
    command: go run migrate.go
    depends_on:
      - db
    volumes:
      - ./server/.env:/go/src/db/migrate/.env
    
volumes:
  mysql_data: