version: "3.8"
services:
  db:
    image: mysql:8.0.27
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_app
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./server/:/go/src/
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true
    stdin_open: true

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    
volumes:
  mysql_data: