version: "3.8"
services:
  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
      
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./server/:/go/src/
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true
    stdin_open: true
    
volumes:
  mysql_data: