version: "3.8"
services:
  db:
    image: mysql:8.0.27
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_app
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - external_network

  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./server/:/go/src/
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true
    stdin_open: true
    networks:
      - external_network

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    networks:
      - external_network
  
  playwright:
    build: .
    container_name: playwright
    tty: true
    ports:
      - "9323:9323"
      - "8010:8010"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DISPLAY=:10
    networks:
      - external_network

networks:
  external_network:
    
volumes:
  mysql_data: